from __future__ import annotations
from typing import Protocol, runtime_checkable
from controller.models import (
    Thread, Job, ThreadStatus, JobStatus, Artifact,
    SwarmGroup, SwarmAgent, SwarmStatus, AgentStatus,
)


@runtime_checkable
class StateBackend(Protocol):
    async def get_thread(self, thread_id: str) -> Thread | None: ...
    async def upsert_thread(self, thread: Thread) -> None: ...
    async def update_thread_status(self, thread_id: str, status: ThreadStatus, job_name: str | None = None) -> None: ...
    async def create_job(self, job: Job) -> None: ...
    async def get_job(self, job_id: str) -> Job | None: ...
    async def get_active_job_for_thread(self, thread_id: str) -> Job | None: ...
    async def get_latest_job_for_thread(self, thread_id: str) -> Job | None: ...
    async def update_job_status(self, job_id: str, status: JobStatus, result: dict | None = None) -> None: ...
    async def append_conversation(self, thread_id: str, message: dict) -> None: ...
    async def get_conversation(self, thread_id: str, limit: int = 50) -> list[dict]: ...
    async def list_threads(self) -> list[Thread]: ...
    async def try_acquire_lock(self, thread_id: str) -> bool: ...
    async def release_lock(self, thread_id: str) -> None: ...
    async def create_artifact(self, task_id: str, artifact: Artifact) -> None: ...
    async def get_artifacts_for_task(self, task_id: str) -> list[Artifact]: ...
    async def create_swarm_group(self, group: SwarmGroup) -> None: ...
    async def get_swarm_group(self, group_id: str) -> SwarmGroup | None: ...
    async def update_swarm_status(self, group_id: str, status: SwarmStatus) -> None: ...
    async def create_swarm_agent(self, agent: SwarmAgent) -> None: ...
    async def update_swarm_agent(self, group_id: str, agent_id: str, status: AgentStatus, result_summary: dict | None = None) -> None: ...
    async def list_swarm_agents(self, group_id: str) -> list[SwarmAgent]: ...
    async def list_swarm_groups(self, status_in: list[SwarmStatus] | None = None) -> list[SwarmGroup]: ...
