from __future__ import annotations
from typing import Protocol, runtime_checkable
from controller.models import Thread, Job, ThreadStatus, JobStatus, Artifact


@runtime_checkable
class StateBackend(Protocol):
    async def get_thread(self, thread_id: str) -> Thread | None: ...
    async def upsert_thread(self, thread: Thread) -> None: ...
    async def update_thread_status(self, thread_id: str, status: ThreadStatus, job_name: str | None = None) -> None: ...
    async def create_job(self, job: Job) -> None: ...
    async def get_job(self, job_id: str) -> Job | None: ...
    async def get_active_job_for_thread(self, thread_id: str) -> Job | None: ...
    async def get_latest_job_for_thread(self, thread_id: str) -> Job | None: ...
    async def update_job_status(self, job_id: str, status: JobStatus, result: dict | None = None) -> None: ...
    async def append_conversation(self, thread_id: str, message: dict) -> None: ...
    async def get_conversation(self, thread_id: str, limit: int = 50) -> list[dict]: ...
    async def list_threads(self) -> list[Thread]: ...
    async def try_acquire_lock(self, thread_id: str) -> bool: ...
    async def release_lock(self, thread_id: str) -> None: ...
    async def create_artifact(self, task_id: str, artifact: Artifact) -> None: ...
    async def get_artifacts_for_task(self, task_id: str) -> list[Artifact]: ...
